[project]
name = "odoo-addons-oca-maintenance"
version = "18.0.20250207.0"
dependencies = [
    "odoo-addon-base_maintenance==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
